SELECT ID, (CASE
           WHEN S_RANK * 100 / E.TOTAL_COUNT <= 25 THEN 'CRITICAL'
           WHEN S_RANK * 100 / E.TOTAL_COUNT <= 50 THEN 'HIGH'
           WHEN S_RANK * 100 / E.TOTAL_COUNT <= 75 THEN 'MEDIUM'
           ELSE 'LOW' END) AS COLONY_NAME
FROM ( SELECT *,
     RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS S_RANK, COUNT(*) OVER () AS TOTAL_COUNT
     FROM ECOLI_DATA) E
ORDER BY ID ASC;