SELECT P.PRODUCT_ID, P.PRODUCT_NAME, PO.SUM_AMOUNT * P.PRICE AS TOTAL_SALES
FROM (SELECT PRODUCT_ID, SUM(AMOUNT) AS SUM_AMOUNT, PRODUCE_DATE
      FROM FOOD_ORDER
      WHERE PRODUCE_DATE LIKE '2022-05%'
      GROUP BY PRODUCT_ID) PO
        JOIN FOOD_PRODUCT P ON PO.PRODUCT_ID = P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;