SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') as REVIEW_DATE
FROM REST_REVIEW R
JOIN (
    SELECT MEMBER_ID 
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1) MR ON MR.MEMBER_ID = R.MEMBER_ID
JOIN MEMBER_PROFILE P ON P.MEMBER_ID = R.MEMBER_ID
ORDER BY R.REVIEW_DATE ASC, R.REVIEW_TEXT ASC;















# SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
# FROM REST_REVIEW R
#     INNER JOIN (SELECT MEMBER_ID
#                 FROM REST_REVIEW
#                 GROUP BY MEMBER_ID
#                 ORDER BY COUNT(*) DESC
#                 LIMIT 1) MR ON MR.MEMBER_ID = R.MEMBER_ID
#     LEFT JOIN MEMBER_PROFILE P ON P.MEMBER_ID = R.MEMBER_ID
# ORDER BY 3,2;